# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

branches:
  only:
    - master

environment:
  global:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    _R_CHECK_FORCE_SUGGESTS_: true
    USE_RTOOLS: true
    PKGTYPE: win.binary
    WARNINGS_ARE_ERRORS:
    R_VERSION: release
    R_ARCH: x64
    R_BUILD_ARGS: --no-manual --no-build-vignettes
    R_CHECK_ARGS: --no-manual --as-cran --ignore-vignettes

  matrix:
    - R_VERSION: release 
      R_ARCH: x64
      GCC_PATH: mingw_64

    
# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc_deps
  
test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: all-Rout.zip
    name: AllRout

cache:
  - C:\RLibrary -> appveyor.yml
